### ISSUE TITLE
Could not fetch patches list from Hypernode platform.

### ISSUE THREAD

**Issue by DanielSousa** [Hypernode/hypernode-magerun#11]

**Comment by jhoelzl** [comment]
+1

**Comment by gwillem** [comment]
Thanks, on it.

**Comment by JeroenBoersma** [comment]
I think Lets Encrypt isn't fully supported yet on curl

**Comment by gwillem** [comment]
Fixed!

Before:

```
$ curl https://tools.hypernode.com/patches/community/1.9.2.3
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
```

After:

```
$ curl https://tools.hypernode.com/patches/community/1.9.2.3
{"required": []}
```

Had to load the intermediate SSL chain from letsencrypt on the server side, to support clients without a recent CA bundle (like most curls).

**Comment by JeroenBoersma** [comment]
checked, correct

**Comment by DanielSousa** [comment]
- fixed, thanks
  Great work!

**Comment by digitalpianism** [comment]
Still not fixed for me...

**Comment by gwillem** [comment]
@digitalpianism can you post the contents of `curl --version` and `curl https://tools.hypernode.com/patches/community/1.9.2.3` ?

**Comment by digitalpianism** [comment]
@gwillem sure here you go

`curl --version`

curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

`curl https://tools.hypernode.com/patches/community/1.9.2.3`

curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by peterjaap** [comment]
Any news on this @gwillem?

**Comment by digitalpianism** [comment]
Just tried again today and it works fine. I guess that was a problem on the hypernode server.

**Comment by gwillem** [comment]
@digitalpianism any chance that you have updated your CA bundle in the mean time? It should work for almost any browser on the planet except for WinXP ;)

https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

**Comment by digitalpianism** [comment]
@gwillem nope I haven't updated anything in the mean time, it just magically works when I tried again after @peterjaap comment.

**Comment by gwillem** [comment]
Issues getting magically fixed, I like ;)

**Comment by digitalpianism** [comment]
Haha I hate when issues disappears magically but yeah I for sure haven't updated anything in the mean time. Hopefully it won't come back.

**Comment by benjamw** [comment]
Doesn't work for me on Windows 8.1 / PHP 7, any suggestions?

**Comment by peterjaap** [comment]
What, exactly, doesn't work? Error messages?

**Comment by benjamw** [comment]
```
> php n98-magerun.phar sys:module:list:updates
Could not fetch data from Hypernode platform.

> php n98-magerun.phar sys:info:patches
Could not fetch patches list from Hypernode platform.
```

No other errors besides those.

I have curl available through PHP, but do not have curl available through windows command line.
The curl available in PHP is v7.46.0.

Anything else you need, let me know.

**Comment by benjamw** [comment]
Running curl through my MingW64 shell (git bash), it all seems to work and 
`curl https://tools.hypernode.com/patches/community/1.9.2.3`
sends back what looks like a valid response as it shows a patch listed there. (SUPEE-7405 v1.1). So it doesn't seem to be anything wrong on the server end, but possibly some misconfiguration that either doesn't work in PHP 7 or Windows.

**Comment by peterjaap** [comment]
Hmm can't really help you there, I have zero to none experience with Windows.

**Comment by benjamw** [comment]
I threw a breakpoint in the PatchesCommand.php file to see what was going on and get this as the URL: `https://tools.hypernode.com/patches/enterprise\1.13.0.1`

Running that through the curl that worked in my git bash, I got a 404. So that might be part of it...

And I think I just figured it out... when creating the `$_patchUrl` on line `46` of `PatchesCommand.php`, it's using `DS` as a directory separator. This is not valid in windows. URLs should always use a forward slash (`/`) regardless of OS.

Changed `DS` to `'/'` and it's working now.

(I also had to change `https` to `http`, but that's probably a different issue.)

**Comment by peterjaap** [comment]
Right, `DS` is a constant defined in Magento, not a PHP constant. We should change that to `DIRECTORY_SEPARATOR`. Strange that it does work on Macs though.

**Comment by peterjaap** [comment]
I pushed a fix. Can you confirm?

**Comment by benjamw** [comment]
No, it's not the name of the constant that's the issue, it's that on Windows, `DS` = `\`, not `/`, which is creating an invalid URL, because URLs should always use `/`, regardless of OS. Mac's use `/` as DS as well, so that's why it works there.

**Comment by peterjaap** [comment]
What filesystem is Windows using nowaways? Will a forward slash always work? And will a backwards slash always fail? What works in which situations? I was always told Windows uses the backslash where Unix uses the forward slash..

**Comment by benjamw** [comment]
So the issue is that Windows uses back slash ( `\` ) for paths in the OS. PHP knows this, and when it's being run on Windows, sets `DIRECTORY_SEPARATOR` to `"\"`, this is why that constant exists. So it can be used and regardless of which architecture the script is run on, the path is still valid.

Technically, the forward slash ( `/` ) will also work on Windows when dealing with paths, but it's better to use the `DIRECTORY_SEPARATOR` constant to prevent issues should this ever change.

The problem with this script is that `DS` (and therefore, `DIRECTORY_SEPARATOR`) is being used to create a URL. URLs are architecture agnostic and should always be forward slashes. That is why, when creating URLs, you should always use the string `"/"` instead of `DS` or `DIRECTORY_SEPARATOR`. 

When creating **paths** (that will be used to find a resource on a computer): use `DS`or `DIRECTORY_SEPARATOR`
When creating **URLs** (that will be used in a browser or to request a resource over the internet): use `"/"`

Does that make sense?

**Comment by peterjaap** [comment]
Doh. I was confusing the two.
